config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'competitions/new'
  get 'competitions/create'
  devise_for :users
  root to: "pages#home"
  resources :competitions, only: [:new, :create, :show, :index]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :competitions do
    resources :teams, only: [:new, :create, :edit, :update, :destroy] do
      member do
        post 'register'
      end
    end
  end

  resources :membership_requests, only: [] do
    member do
      post 'approve'
    end
  end

  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :sport
  has_many :teams
  has_one_attached :image

  validates :number_of_teams, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :sport_id, :date, :time, :address, :name, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      sql_subquery = <<~SQL
        competitions.address @@ :query
        OR competitions.city @@ :query
        OR competitions.name @@ :query
      SQL
      @competitions = Competition.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @competitions = Competition.all
    end

    # The `geocoded` scope filters only competitions with coordinates
    @markers = @competitions.geocoded.map do |competition|
      {
        lat: competition.latitude,
        lng: competition.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {competition: competition}),
        marker_html: render_to_string(partial: "marker", locals: {competition: competition})
      }
    end
  end

  def show
    @competition = Competition.find(params[:id])
    @team = @competition.teams.new
  end

  def new
    @competition = Competition.new
    @sports = Sport.all # Pour remplir le menu déroulant des sports
  end

  def create
    @competition = Competition.new(competition_params)
    @competition.user = current_user
    if @competition.save
      redirect_to @competition, notice: 'La compétition a été créée avec succès.'
    else
      @sports = Sport.all
      render :new
    end
  end

  def edit
  end

  def update
    if @competition.update(competition_params)
      redirect_to @competition, notice: 'La compétition a été mise à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    if @competition.user == current_user
      @competition.destroy
      redirect_to competitions_path, notice: 'Compétition supprimée avec succès.'
    else
      redirect_to competitions_path, alert: 'Vous n\'êtes pas autorisé à supprimer cette compétition.'
    end
  end

  private

  def set_competition
    @competition = Competition.find(params[:id])
  end

  def competition_params
    params.require(:competition).permit(:name, :description, :date_time, :latitude, :longitude, :address, :number_of_teams, :sport_id, :user_id)
  end
end

app/views/competitions/_competition-card.html.erb
<!-- app/views/competitions/_competition-card.html.erb -->

<% @top_competitions.each_with_index do |competition, index| %>
  <div class="wrapper">
    <%= link_to competition_path(competition), class: 'clash-card-link' do %>
      <div class="clash-card <%= card_class(competition.sport.name) %>">
        <div class="clash-card__image <%= image_class(competition.sport.name) %>">
          <% if competition.image_url.present? %>
            <div class="competition-image">
              <img src="<%= competition.image_url %>" alt="<%= competition.name %>" />
            </div>
          <% end %>
        </div>
        <div class="clash-card__level <%= level_class(competition.sport.name) %>"><%= competition.sport.name %></div>
        <div class="clash-card__unit-name"><%= competition.name %></div>
        <div class="clash-card__unit-description">
          <p><i class="fa-solid fa-location-dot"></i> <%= competition.city %> </p>
          <p><strong class="clash-card__level <%= level_class(competition.sport.name) %>"><%= competition.teams.count %> teams constituées</strong></p>
        </div>
        <div class="clash-card__unit-stats <%= stats_class(competition.sport.name) %> clearfix">
          <div class="one-third">
            <div class="stat"><%= competition.date.strftime("%d.%m.%y") %></div>
            <div class="stat-value">Date</div>
          </div>
          <div class="one-third">
            <div class="stat"><%= competition.time.strftime("%H:%M") %></div>
            <div class="stat-value">Heure</div>
          </div>
          <div class="one-third no-border">
            <div class="stat"><%= formatted_cost(competition.cost) %></div>
            <div class="stat-value">Coût</div>
          </div>
        </div>
      </div> <!-- end clash-card -->
    <% end %>
  </div> <!-- end wrapper -->
<% end %>

app/views/competitions/_info_window.html.erb
<h2 class= "yellow-gradient" style="font-family: 'Bebas Neue'"><%= competition.name %></h2>
<p><%= competition.address %></p>
<%= link_to 'Voir la compétition', competition_path(competition), class: 'btn btn-primary' %>

app/views/competitions/_marker.html.erb
<%= image_tag "Map_pin.png", height: 30, width: 30, alt: "avatar" %>
<div class="badge rounded-pill bg-primary fs-6">
  <%= competition.cost %>€
</div>

app/views/competitions/_team_card.html.erb
<h1><%= @competition.name %></h1>
<p><%= @competition.description %></p>

<div class="teams">
  <% @competition.teams.each do |team| %>
    <div class="team-card">
      <h2><%= team.name %></h2>
      <p><%= team.description %></p>
      <!-- Bouton de demande d'inscription -->
      <%= link_to 'Demander à rejoindre l\'équipe', register_competition_team_path(@competition, team), method: :post, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/competitions/create.html.erb
<h1>Competitions#create</h1>
<p>Find me in app/views/competitions/create.html.erb</p>

app/views/competitions/index.html.erb
<div>
  <h1 class="mt-5 yellow-gradient" style="font-family: 'Bebas Neue', sans-serif; font-weight: 400; font-style: normal; font-size: 60px;">
    TOUTES NOS COMPETITIONS 🎉
  </h1>

  <!-- Banner -->
  <div class="banner-competition-content py-5">
    <div class="banner-competitions" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url(<%= asset_path('index_banner.jpg') %>);">

      <h1>
        Choisis ta compétition. <i class="fas fa-trophy" style="margin-right: 10px"></i>
      </h1>
    </div>
  </div>


  <div class="index-page">
    <div class="main-container">

        <!-- Search bar and cards -->
       <div class="sidebar">
    <div class="search-bar mb-4">
  <%= form_with url: competitions_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query, params[:query], class: "form-control search-input", placeholder: "Recherche ...", aria: { label: "Search" } %>
    <%= submit_tag "Go !", name: "", class: "btn btn-primary search-button" %>
  <% end %>
</div>

        <div class="slide-container row">
          <% @competitions.each do |competition| %>
            <div class="col-lg-4 col-md-6 wrapper">
              <%= link_to competition_path(competition), class: 'clash-card-link' do %>
                <div class="clash-card <%= card_class(competition.sport.name) %>">
                  <div class="clash-card__image <%= image_class(competition.sport.name) %>">
                    <% if competition.image_url.present? %>
                      <div class="competition-image">
                        <img src="<%= competition.image_url %>" alt="<%= competition.name %>" />
                      </div>
                    <% end %>
                  </div>
                  <div class="clash-card__level <%= level_class(competition.sport.name) %>"><%= competition.sport.name %></div>
                  <div class="clash-card__unit-name"><%= competition.name %></div>
                  <div class="clash-card__unit-description">
                    <p><i class="fa-solid fa-location-dot"></i> <%= competition.city %> </p>
                    <p><strong class="clash-card__level <%= level_class(competition.sport.name) %>"><%= competition.teams.count %> teams constituées</strong></p>
                  </div>
                  <div class="clash-card__unit-stats <%= stats_class(competition.sport.name) %> clearfix">
                    <div class="one-third">
                      <div class="stat"><%= competition.date.strftime("%d.%m.%y") %></div>
                      <div class="stat-value">Date</div>
                    </div>
                    <div class="one-third">
                      <div class="stat"><%= competition.time.strftime("%H:%M") %></div>
                      <div class="stat-value">Heure</div>
                    </div>
                    <div class="one-third no-border">
                      <div class="stat"><%= formatted_cost(competition.cost) %></div>
                      <div class="stat-value">Coût</div>
                    </div>
                  </div>
                </div> <!-- end clash-card -->
              <% end %>
            </div> <!-- end wrapper -->
          <% end %>
        </div> <!-- end slide-container -->
      </div> <!-- end sidebar -->



      <!-- Map -->
      <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-query-value="<%= params[:query] %>">
    </div>

    </div> <!-- end main-content -->
  </div> <!-- end container -->

</div>

app/views/competitions/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mt-4">
      <h2>Créer une compétition</h2>
      <div>
        <%= simple_form_for(@competition, html: { multipart: true }) do |form| %>
          <div class="form-inputs mt-4">
            <%= form.input :name, label: "Nom de la compétition", input_html: { class: 'field-bg-color field-no-border', placeholder: "Nom de la compétition" } %>
            <%= form.input :sport_id, collection: @sports, label: "Sport", input_html: { class: 'field-bg-color field-no-border' } %>
            <%= form.input :number_of_teams, label: "Nombre d'équipes maximum", input_html: { class: 'field-bg-color field-no-border', type: 'number', min: '1' } %>
            <%= form.input :date_time, label: "Date & heure", input_html: { class: 'field-bg-color field-no-border', placeholder: "Date et heure de l'évènement" }, wrapper_html: { class: 'mb-3' }, html5: true %>
            <%= form.input :address, label: "Adresse", input_html: { class: 'field-bg-color field-no-border', placeholder: "Adresse de l'évènement" } %>
          </div>
          <div class="actions">
            <%= form.submit "Créer la compétition" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/competitions/show.html.erb
<!-- app/views/competitions/show.html.erb -->
<div class="container see-team mt-4" data-controller="join-team">
  <div class="row">
    <!-- Section principale -->
    <div class="col-md-9">
      <div class="bg-light p-4 rounded shadow-sm">
        <% sport_color = case @competition.sport.name
                          when 'Badminton'
                            '#82bb30'
                          when 'Tennis'
                            '#176cc7'
                          when 'Padel'
                            '#f69019'
                          when 'Ping-pong'
                            '#ee5487'
                          else
                            '#000000' # couleur par défaut ou autre traitement
                          end %>

        <h1 class="mb-5" style="color: <%= sport_color %>;">   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.name %></h2>
        <p><strong><i class="fa-solid fa-trophy"></i></strong>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.sport.name %></p>
        <p><strong><i class="fa-solid fa-people-group"></i></strong>   &nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.teams.count %> équipes</p>
        <p><strong><i class="fa-solid fa-calendar-days"></i></strong>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.date.strftime('%d %B %Y') %></p>
        <p><strong><i class="fa-solid fa-clock"></i></strong>   &nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.time.strftime('%Hh%M') %></p>
        <p><strong><i class="fa-solid fa-location-dot"></i></strong>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @competition.address %></p>
        <%= link_to "Retour à la liste des compétitions", competitions_path, class: "btn btn-outline-primary team-button mt-3 mb-2", style: "color: #{sport_color}; border-color: #{sport_color};" %>
      </div>
    </div>

<div class="col-md-9">
  <div class="mt-4 p-4 rounded shadow-sm rounded bg-light">
    <h3 class="text-secondary mb-4">Équipes inscrites</h3>
    <div class="row">
      <% @competition.teams.order(created_at: :desc).each do |team| %>
        <div class="col-md-4 mb-4">
          <%= link_to user_path(team.owner_id), class: 'text-decoration-none' do %>
            <div class='h-100'>
              <div class="card-body team1" style="background-color:#FFFFFF;border: 1px solid <%= sport_color %>;">
                <h5 class="card-title" style="color: <%= sport_color %>;"><%= team.name %></h5><br>
                <p class="card-text team1"><strong class="text-dark"><i class="fa-solid fa-user-group"></i></strong> <span class="text-muted"><%= team.number_max_of_participants %> participants MAX</span></p><br>
                <p class="card-text team1"><strong class="text-dark">Créateur de l'équipe :</strong> <span class="text-muted"><%= User.find(team.owner_id).name %></span></p><br>
                <button class="btn btn-primary btn-sm mt-3 mb-2 w-100" style="background-color: <%= sport_color %>; border-color: <%= sport_color %>;" data-action="click->join-team#openModal" data-team-id="<%= team.id %>" data-team-chatroom-url="<%= chatroom_path(team.chatroom) %>">Rejoindre</button>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

    <!-- Section pour ajouter une nouvelle équipe -->
    <div class="col-md-3 mt-4">
      <div class="bg-light p-4 rounded shadow-sm">
        <h4 class="text-success">Ajouter une équipe</h4>
        <%= simple_form_for([@competition, @competition.teams.build], url: competition_teams_path(@competition), html: { class: 'form-horizontal' }) do |f| %>
          <% if @team.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h5><%= pluralize(@team.errors.count, "erreur") %> ont empêché l'enregistrement de l'équipe :</h5>
              <ul>
                <% @team.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.input :name, label: 'Nom de l\'équipe', input_html: { class: 'form-control' } %>
          </div>
          <div class="form-group">
            <%= f.input :number_max_of_participants, label: 'Nombre maximum de participants', input_html: { class: 'form-control', min: 0 } %>
          </div>
          <div class="form-group">
            <%= f.submit 'Ajouter l\'équipe', class: 'btn btn-success btn-block', style: "background-color: #{sport_color}; border-color: #{sport_color};" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Modale pour rejoindre une équipe -->
<div class="modal see-team-modal" data-join-team-target="modal">
  <% sport_color = case @competition.sport.name
                          when 'Badminton'
                            '#82bb30'
                          when 'Tennis'
                            '#176cc7'
                          when 'Padel'
                            '#f69019'
                          when 'Ping-pong'
                            '#ee5487'
                          else
                            '#000000' # couleur par défaut ou autre traitement
                          end %>
  <div class="modal-background" data-action="click->join-team#close"></div>
  <div class="modal-content">
    <button class="modal-close is-large" aria-label="close" data-action="click->join-team#close">&times;</button>
    <div class="modal-body team1">
      <h3 class="modal-title" style="color: <%= sport_color %>;">Bienvenue dans la team !</h3>
      <p class="modal-text">Nous sommes ravis de t'avoir avec nous. Que l'aventure commence !</p>
      <button class="btn btn-secondary team-button" data-action="click->join-team#close">Retour aux équipes</button>
      <button class="btn btn-primary team-button" style="background-color: <%= sport_color %>; border-color: <%= sport_color %>;" data-action="click->join-team#goToChatroom">Discuter avec mes équipiers</button>
    </div>
  </div>
</div>
</div>