config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'competitions/new'
  get 'competitions/create'
  devise_for :users
  root to: "pages#home"
  resources :competitions, only: [:new, :create, :show, :index]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

  resources :competitions do
    resources :teams, only: [:new, :create, :edit, :update, :destroy] do
      member do
        post 'register'
      end
    end
  end

  resources :membership_requests, only: [] do
    member do
      post 'approve'
    end
  end

  resources :users, only: [:show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container-fluid custom-max-width d-flex justify-content-between align-items-center">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      La Team de la victoire vous attend sur TeamMatch... <i class="fas fa-heart"></i>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between align-items-center custom-max-width", style="margin-top:0px">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('Logo_TeamMatch.png') %>
    <% end %>

    <div class="d-flex justify-content-end align-items-center flex-grow-1">
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messagerie", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag asset_path('Avatar.png'), class: "avatar", alt: "avatar profile image" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>